### ISSUE TITLE
[2020] Week #14

### ISSUE THREAD

**Issue by qlinkDev** [qlcchain/QWallet-Android#49]
#45 Interface change on Neo chain, claim function change in wallet
#46 Manage multiple chain wallets with the same mnemonic
#47 Buried points of main functional modules
#48 The display speed of the home page is optimized, and the related content of the home page is loaded in advance or the configuration file is loaded

**Comment by huzhipeng111** [comment]
1, Interface change on Neo chain, claim function change in wallet
2, Manage multiple chain wallets with the same mnemonic
3, Buried points of main functional modules (Android and IOS use the same configuration file to communicate where the burying point is)
4, The display speed of the home page is optimized, and the related content of the home page is loaded in advance or the configuration file is loaded

**Comment by huzhipeng111** [comment]
#45 
#46 
#47 
#50 
#51

**Comment by huzhipeng111** [comment]
#45 
#46 
#47 
#50 
#51
