### ISSUE TITLE
QWallet bug with QLC Cross-chain Swap

### ISSUE THREAD

**Issue by andripi** [qlcchain/QWallet-Android#93]
QLC Cross-chain Swap feature is only available when app is loaded with NEO Wallet selected. When switching to QLC Chain-Wallet and then back to NEO Wallet, swap option disappears. The same if app is started with QLC Chain wallet and then switch to NEO wallet, option to swap is not available.

**Comment by qlinkDev** [comment]
Function delay, please operate on the web wallet
